module.exports = {
    stupidBusinessBuzzwords: [
        "artificial intelligence",
        "business analytics",
        "marketing",
        "ecosystem",
        "synergy",
        "think outside the box",
        "let's step back and think about this",
        "Circle back",
        "Low-hanging fruit",
        "At the end of the day",
        "Cloud based",
        "To not know what you don't know",
        "Big data",
        "Move the needle",
        "Leverage",
        "agile",
        "best practice",
        "digital transformation",
        "deep dive",
        "bandwidth",
        "customer journey",
        "moving forward",
        "going forward",
        "next level",
        "reach out",
        "touch base",
        "wheelhouse",
        "disruptor",
        "alignment",
        "right",
        "bottom line",
        "FYI",
        "KPI",
        "ROI",
        "distruptive",
        "value",
        "ping",
        "lean into",
        "paradigm",
        "learnings",
        "holistic approach",
        "company culture",
        "thought leader",
        "content",
        "growth hacking",
        "buy in",
        "pain point",
        "lane",
        "game-changer",
        "teamwork",
        "Next-gen",
        "Hard stop",
        "Internet of things",
        "IoT",
        "innovative",
        "influencer",
        "customer-centric",
        "all hands on deck",
        "net",
        "put a pin in it",
        "stakeholders",
        "strategic",
        "metrics",
        "machine learning",
        "pivot",
        "on the same page",
        "collaboration",
        "Intelligence",
        "business intelligence",
        "competitive intelligence",
        "automation",
        "blockchain",
        "intuitive",
        "analytics",
        "platform",
        "unpack",
        "table",
        "giving 110%",
        "quick win",
        "onboarding",
        "long story short",
        "full plate",
        "looping back",
        "in the loop",
        "freemium",
        "integration",
        "engagement",
        "actionable",
        "efficiency",
        "hemmoraging",
        "money",
        "socialize",
        "diversity",
        "verticals",
        "bleeding-edge",
        "optimize",
        "scalable",
        "organic",
        "empower",
        "win-win",
        "optics",
        "data-driven",
        "in the weeds",
        "on your radar",
        "ducks in a row",
        "drill down",
        "playing in the space of",
        "fast-paced",
        "mindfullness",
        "as per my last email",
        "ASAP",
        "BID",
        "EOD",
        "ETA",
        "DOA",
        "IMO",
        "month over month",
        "year over year",
        "quarterly",
        "WFH"
    ],
    connectors: [
        "of",
        "to",
        "for",
        "with",
        "by",
        "from",
        "about",
        "in",
        "on",
        "at",
        "into",
        "onto",
        "off",
        "out",
        "over",
        "under",
        "up",
        "down",
        "around",
        "through",
        "that",
        "this",
        "these",
        "those",
        "it",
        "its",
        "a",
        "an",
        "the"
    ],
    haskellBuzzWords: [
        
    ]
}